### ISSUE TITLE
Problems with this Snap

### ISSUE THREAD

**Issue by rebastion** [srevinsaju/element-snap#1]
See

https://github.com/vector-im/element-web/issues/14916#event-3648170594

**Comment by srevinsaju** [comment]
The snap cannot be containerised as far as I have tried, I can give a solution to you anyway:
* use the AppImage (almost official, https://github.com/srevinsaju/element-appimage
* I would demote the snap to `--devmode`. The problem is that, Element tries to access `/dev/shm` aka Shared Memory which is not preferred for a containerised app.

**Comment by srevinsaju** [comment]
@rebastion I have demoted to devmode, if you would like to try again

**Comment by rebastion** [comment]
I just switched to the official installer method from the Element website instead, sorry

**Comment by srevinsaju** [comment]
I will just remove the snap from the snap store in case any one installs this on mistake 😅

**Comment by rebastion** [comment]
Also a good idea :) But thank you for your efforts!
